version: "3"
services:
  node:
    image: "node:10"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: bash -c "npm install && yarn install && yarn build"
