version: "3"
services:
  node:
    image: "node:10"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8001"
    command: bash -c "npm install && yarn install && yarn build && tail -f nginx.conf"
  react_server:
    image: nginx
    environment:
      - NGINX_PORT=8000
    volumes:
      - .:/home/node/app
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    working_dir: /home/node/app
    ports:
      - '8000:8000'
      - '444:444'
    entrypoint: bash -c "service nginx start && tail -f nginx.conf"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - reat_certbot
  reat_certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - node
